### ISSUE TITLE
npm start with error

### ISSUE THREAD

**Issue by RunningV** [josephfinlayson/react-es6#1]
Excuse me, I clone ur file, and `npm install` all right, but when i run `npm start`, there a some error that can't run : 

```
 npm start

> react-es6-demo@0.1.0 start E:\Running\web\react\react-es6-demo
> babel-node -- ./node_modules/.bin/webpack-dev-server

E:\Running\web\react\react-es6-demo\node_modules\.bin\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Running\web\react\react-es6-demo\node_modules\babel-register\lib\node.js:166:7)
```

i dont know how to solve it, i like ur project to use `es6` and `import` snytax write react code .pls help me, tks.

**Comment by bogdandevlpr** [comment]
i also have this issue
